triggers:
  #TODO 
  - id: 1  # test
    type: circle
    level: L1
    x: 11.3
    y: 0.516
    radius: 2.0
    message: "Inspect firehydrants before fire extinguishers."
  
  - id: 2
    type: circle
    level: L1
    x: 43.00
    y: 8.00
    radius: 2.0
    message: "Don't enter the H5 hallway."

  - id: 3
    type: circle
    level: L2
    x: 11.84
    y: 21.86
    radius: 2.0
    message: "UGV2 is malfunctioning."
  
  - id: 4
    type: line
    level: L2
    x: 17.8
    y: 0.565
    threshold: 1.0
    message: "Don't enter the seminar room. It is currently in use."